apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: catalogue
spec:
  replicas: 5
  selector:
    matchLabels:
      app: catalogue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: catalogue
    spec:
      containers:
      - image: nginx:1.14.2
        name: catalogue
        ports:
        - containerPort: 80
          name: catalogue-tcp
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - ls
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "1"
            memory: 10Gi
          requests:
            cpu: 500m
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: catalogue-service
      terminationGracePeriodSeconds: 30
status: {}
